# Generated by Django 2.2.5 on 2019-10-06 22:56

import apps.user.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '未知')], default=3, verbose_name='性别')),
                ('birthday', models.DateTimeField(default=datetime.datetime.now, verbose_name='出生日期')),
                ('say_sth', models.CharField(default='这个人懒死了，什么都没有写╮(╯▽╰)╭', max_length=25, verbose_name='签名')),
            ],
            options={
                'verbose_name': '其他用户信息',
                'verbose_name_plural': '其他用户信息',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('nickname', models.CharField(default='无名', max_length=10, verbose_name='昵称')),
                ('face', models.ImageField(default='default_face.jpg', upload_to=apps.user.models.custom_path, verbose_name='封面')),
                ('random', models.UUIDField(default=uuid.uuid4, verbose_name='随机码')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('other_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.OtherInfo', verbose_name='其他用户信息')),
            ],
            options={
                'verbose_name': '基本用户信息',
                'verbose_name_plural': '基本用户信息',
            },
        ),
    ]
