# Generated by Django 2.2.5 on 2019-10-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwt',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='JWT'),
        ),
    ]
