# Generated by Django 2.2.5 on 2019-10-15 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191015_2353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInterest',
        ),
    ]
