# Generated by Django 2.2.5 on 2019-10-14 22:20

import apps.film.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='演员')),
                ('desc', models.TextField(verbose_name='演员生涯')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.film.models.custom_path, verbose_name='演员照片')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '演员',
                'verbose_name_plural': '演员',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='电影名称')),
                ('cover', models.ImageField(upload_to=apps.film.models.custom_path, verbose_name='封面')),
                ('is_swiper', models.BooleanField(default=False, verbose_name='是否轮播')),
                ('swiper_img', models.ImageField(blank=True, null=True, upload_to=apps.film.models.custom_path, verbose_name='轮播图片')),
                ('trailer', models.FileField(blank=True, null=True, upload_to=apps.film.models.custom_path, verbose_name='视频内容')),
                ('score', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='分数')),
                ('prised_count', models.IntegerField(verbose_name='点赞数')),
                ('basic_info', models.CharField(max_length=100, verbose_name='基本信息')),
                ('original_name', models.CharField(max_length=30, verbose_name='影片原名')),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上映时间')),
                ('release_place', models.CharField(max_length=10, verbose_name='上映地点')),
                ('total_time', models.IntegerField(verbose_name='影片时长')),
                ('plot_desc', models.TextField(verbose_name='剧情描述')),
                ('directors', models.CharField(max_length=30, verbose_name='导演')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热门')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '影片',
                'verbose_name_plural': '影片',
            },
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(upload_to=apps.film.models.custom_path, verbose_name='海报')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='film.Film', verbose_name='电影')),
            ],
            options={
                'verbose_name': '海报',
                'verbose_name_plural': '海报',
            },
        ),
        migrations.CreateModel(
            name='FilmActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=20, null=True, verbose_name='出演角色')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.Actor')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.Film')),
            ],
            options={
                'verbose_name': '演员和电影的索引表',
                'verbose_name_plural': '演员和电影的索引表',
            },
        ),
        migrations.AddField(
            model_name='film',
            name='actor',
            field=models.ManyToManyField(through='film.FilmActor', to='film.Actor', verbose_name='演员'),
        ),
    ]
