# Generated by Django 2.2.5 on 2019-10-14 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='is_swiper',
        ),
    ]
