# Generated by Django 2.2.5 on 2019-09-19 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='film',
        ),
        migrations.AddField(
            model_name='actor',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 9, 19, 22, 48, 13, 448629), verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='actor',
            field=models.ManyToManyField(through='film.FilmActor', to='film.Actor', verbose_name='演员'),
        ),
        migrations.AddField(
            model_name='filmactor',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 9, 19, 22, 48, 29, 304536), verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poster',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 9, 19, 22, 48, 32, 622726), verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
