# Generated by Django 2.2.5 on 2019-09-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_auto_20190919_2248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmactor',
            options={'verbose_name': '演员和电影的索引表', 'verbose_name_plural': '演员和电影的索引表'},
        ),
        migrations.AddField(
            model_name='film',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='是否热门'),
        ),
    ]
