# Generated by Django 2.2.5 on 2019-10-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_remove_film_is_swiper'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='is_swiper',
            field=models.BooleanField(default=False, verbose_name='是否轮播'),
        ),
    ]
