# Generated by Django 2.2.5 on 2019-09-20 11:31

import apps.film.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_auto_20190920_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.film.models.custom_path, verbose_name='演员照片'),
        ),
    ]
