# Generated by Django 2.2.5 on 2019-09-20 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_actor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='film.Film', verbose_name='电影'),
        ),
    ]
